//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        internal static string Ad {
            get {
                return ResourceManager.GetString("Ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlanlar.
        /// </summary>
        internal static string AdDetails {
            get {
                return ResourceManager.GetString("AdDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bina Yaşı.
        /// </summary>
        internal static string BAge {
            get {
                return ResourceManager.GetString("BAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banyo Sayısı.
        /// </summary>
        internal static string Bath {
            get {
                return ResourceManager.GetString("Bath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIZE.
        /// </summary>
        internal static string BOYUT {
            get {
                return ResourceManager.GetString("BOYUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola Tekrarı.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçerik.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kredi.
        /// </summary>
        internal static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje Teslim Tarihi.
        /// </summary>
        internal static string DeliveryDate {
            get {
                return ResourceManager.GetString("DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DETAYLI İNCELE.
        /// </summary>
        internal static string detayliincele {
            get {
                return ResourceManager.GetString("detayliincele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DETAYLI İNCELE.
        /// </summary>
        internal static string detayliincele1 {
            get {
                return ResourceManager.GetString("detayliincele1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlçe.
        /// </summary>
        internal static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aidat.
        /// </summary>
        internal static string Dues {
            get {
                return ResourceManager.GetString("Dues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danışman.
        /// </summary>
        internal static string Expert {
            get {
                return ResourceManager.GetString("Expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kat Sayısı.
        /// </summary>
        internal static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eşya.
        /// </summary>
        internal static string Goods {
            get {
                return ResourceManager.GetString("Goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlık.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isıtma.
        /// </summary>
        internal static string Heat {
            get {
                return ResourceManager.GetString("Heat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kat Sayısı.
        /// </summary>
        internal static string HouseN {
            get {
                return ResourceManager.GetString("HouseN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokasyon.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haritalar.
        /// </summary>
        internal static string Maps {
            get {
                return ResourceManager.GetString("Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj İçeriği.
        /// </summary>
        internal static string MessageContent {
            get {
                return ResourceManager.GetString("MessageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj.
        /// </summary>
        internal static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adı.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YENİ EKLENENLER.
        /// </summary>
        internal static string newadded {
            get {
                return ResourceManager.GetString("newadded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROOM.
        /// </summary>
        internal static string ODA {
            get {
                return ResourceManager.GetString("ODA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon Numarası.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje Alanı.
        /// </summary>
        internal static string ProjectA {
            get {
                return ResourceManager.GetString("ProjectA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projeler.
        /// </summary>
        internal static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özellikler.
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İl.
        /// </summary>
        internal static string Provinces {
            get {
                return ResourceManager.GetString("Provinces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cevap.
        /// </summary>
        internal static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konu Başlığı.
        /// </summary>
        internal static string ReplyTitle {
            get {
                return ResourceManager.GetString("ReplyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oda.
        /// </summary>
        internal static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARAMA YAPIN.
        /// </summary>
        internal static string SearchText {
            get {
                return ResourceManager.GetString("SearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boyut.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAYALİNİZDEKİ.
        /// </summary>
        internal static string Slider1 {
            get {
                return ResourceManager.GetString("Slider1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVE KAVUŞUN.
        /// </summary>
        internal static string Slider2 {
            get {
                return ResourceManager.GetString("Slider2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 DİLDE HİZMET VERİYORUZ.
        /// </summary>
        internal static string SliderAlt {
            get {
                return ResourceManager.GetString("SliderAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hayalini kurduğunuz eve ulaşmak çok kolay! Hemen istediğiniz kriterlerdeki evi aratın, uzmanlarımızdan yardım alın, yeni evinize hemen yerleşin!.
        /// </summary>
        internal static string SliderText {
            get {
                return ResourceManager.GetString("SliderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje Konumu.
        /// </summary>
        internal static string SSubName {
            get {
                return ResourceManager.GetString("SSubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma Adı.
        /// </summary>
        internal static string SubName {
            get {
                return ResourceManager.GetString("SubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt Başlık.
        /// </summary>
        internal static string SubText {
            get {
                return ResourceManager.GetString("SubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad.
        /// </summary>
        internal static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazı.
        /// </summary>
        internal static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unvan.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 DİLDE HİZMET VERİYORUZ..
        /// </summary>
        internal static string Uzman1 {
            get {
                return ResourceManager.GetString("Uzman1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UZMANLARIMIZ.
        /// </summary>
        internal static string Uzman2 {
            get {
                return ResourceManager.GetString("Uzman2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HİZMETİNİZDE.
        /// </summary>
        internal static string Uzman3 {
            get {
                return ResourceManager.GetString("Uzman3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BİR UZMANA BAŞVUR.
        /// </summary>
        internal static string UzmanButonText {
            get {
                return ResourceManager.GetString("UzmanButonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sektörde tecrübe kazanmış uzmanlarımız size ihtiyacınız olan evi bulmaya daima hazırdır.
        /// </summary>
        internal static string UzmanDetay {
            get {
                return ResourceManager.GetString("UzmanDetay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISTRICT.
        /// </summary>
        internal static string İLÇE {
            get {
                return ResourceManager.GetString("İLÇE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CITY.
        /// </summary>
        internal static string ŞEHİR {
            get {
                return ResourceManager.GetString("ŞEHİR", resourceCulture);
            }
        }
    }
}
